modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="soda"
version="0.2.8"
displayName="Soda Mod"
credits="Myself"
displayURL="https://discord.gg/9xnVJxu"
logoFile="logo.png"
authors="ShinyyEevee"
description='''
Shinyy's General Soda Mod
'''

[[dependencies.soda]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




