modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="soda"
version="0.3.2"
displayName="Soda Mod"
credits="Myself"
displayURL="https://www.curseforge.com/minecraft/mc-mods/shinyys-soda-mod/"
logoFile="logo.png"
authors="ShinyyEevee"
description='''
Shinyy's General Soda Mod
'''

[[dependencies.soda]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




